apiVersion: v2
description: Hybrasyl Server
name: server
version: 0.9.6
appVersion: 0.9.5
home: https://www.hybrasyl.com
maintainers:
  - name: ERISCO, LLC
    url: https://github.com/hybrasyl/server
dependencies:
  - name: valkey
    version: 0.10.0
    repository: https://valkey.io/valkey-helm
    condition: valkey.enabled
