{{- if .Values.server.logging.singleStream.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.environment }}-gameserver-logs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hybrasyl.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.logging.singleStream.size | default "1Gi" }}
  {{- if .Values.server.logging.singleStream.storageClass }}
  storageClassName: {{ .Values.server.logging.singleStream.storageClass }}
  {{- end }}
{{- end }}
