---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hybrasyl-pod-server-access
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hybrasyl.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hybrasyl.fullname" . }}-read-services
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hybrasyl.fullname" . }}-read-services
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hybrasyl.fullname" . }}-read-services
subjects:
- kind: ServiceAccount
  name: hybrasyl-pod-server-access
  namespace: {{ .Release.Namespace }}
