{{- if or .Values.secrets.githubSshKey .Values.secrets.grpcChainCert .Values.secrets.redisPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hybrasyl.fullname" . }}-settings
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hybrasyl.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if .Values.secrets.githubSshKey }}
  github-ssh.key: |
    {{ .Values.secrets.githubSshKey | nindent 4 }}
{{- end }}
{{- if .Values.secrets.grpcChainCert }}
  grpc-chain.pem: |
    {{ .Values.secrets.grpcChainCert | nindent 4 }}
{{- end }}
{{- if .Values.secrets.redisPassword }}
  redis-password: {{ .Values.secrets.redisPassword | quote }}
{{- end }}
{{- end }}
