#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Hybrasyl	
{
	public partial class mobs
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private int _sprite;
		public virtual int Sprite
		{
			get
			{
				return this._sprite;
			}
			set
			{
				this._sprite = value;
			}
		}
		
		private DateTime _created_at;
		public virtual DateTime Created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				this._created_at = value;
			}
		}
		
		private DateTime _updated_at;
		public virtual DateTime Updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				this._updated_at = value;
			}
		}
		
		private int _level;
		public virtual int Level
		{
			get
			{
				return this._level;
			}
			set
			{
				this._level = value;
			}
		}
		
		private int _min_dmg;
		public virtual int Min_dmg
		{
			get
			{
				return this._min_dmg;
			}
			set
			{
				this._min_dmg = value;
			}
		}
		
		private int _max_dmg;
		public virtual int Max_dmg
		{
			get
			{
				return this._max_dmg;
			}
			set
			{
				this._max_dmg = value;
			}
		}
		
		private int _mr;
		public virtual int Mr
		{
			get
			{
				return this._mr;
			}
			set
			{
				this._mr = value;
			}
		}
		
		private int _ac;
		public virtual int Ac
		{
			get
			{
				return this._ac;
			}
			set
			{
				this._ac = value;
			}
		}
		
		private float _force_multiplier;
		public virtual float Force_multiplier
		{
			get
			{
				return this._force_multiplier;
			}
			set
			{
				this._force_multiplier = value;
			}
		}
		
		private int _off_element;
		public virtual int Off_element
		{
			get
			{
				return this._off_element;
			}
			set
			{
				this._off_element = value;
			}
		}
		
		private int _def_element;
		public virtual int Def_element
		{
			get
			{
				return this._def_element;
			}
			set
			{
				this._def_element = value;
			}
		}
		
		private int _exp;
		public virtual int Exp
		{
			get
			{
				return this._exp;
			}
			set
			{
				this._exp = value;
			}
		}
		
		private int _gold;
		public virtual int Gold
		{
			get
			{
				return this._gold;
			}
			set
			{
				this._gold = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private string _script_name;
		public virtual string Script_name
		{
			get
			{
				return this._script_name;
			}
			set
			{
				this._script_name = value;
			}
		}
		
	}
}
#pragma warning restore 1591
