#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Hybrasyl	
{
	public partial class news_posts
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _account_id;
		public virtual int Account_id
		{
			get
			{
				return this._account_id;
			}
			set
			{
				this._account_id = value;
			}
		}
		
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private string _post;
		public virtual string Post
		{
			get
			{
				return this._post;
			}
			set
			{
				this._post = value;
			}
		}
		
		private DateTime _created_at;
		public virtual DateTime Created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				this._created_at = value;
			}
		}
		
		private DateTime _updated_at;
		public virtual DateTime Updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				this._updated_at = value;
			}
		}
		
		private DateTime? _post_date;
		public virtual DateTime? Post_date
		{
			get
			{
				return this._post_date;
			}
			set
			{
				this._post_date = value;
			}
		}
		
	}
}
#pragma warning restore 1591
