#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Hybrasyl	
{
	public partial class spawn_points
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _map_id;
		public virtual int Map_id
		{
			get
			{
				return this._map_id;
			}
			set
			{
				this._map_id = value;
			}
		}
		
		private int _map_x;
		public virtual int Map_x
		{
			get
			{
				return this._map_x;
			}
			set
			{
				this._map_x = value;
			}
		}
		
		private int _map_y;
		public virtual int Map_y
		{
			get
			{
				return this._map_y;
			}
			set
			{
				this._map_y = value;
			}
		}
		
		private DateTime _created_at;
		public virtual DateTime Created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				this._created_at = value;
			}
		}
		
		private DateTime _updated_at;
		public virtual DateTime Updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				this._updated_at = value;
			}
		}
		
		private int _nation_id;
		public virtual int Nation_id
		{
			get
			{
				return this._nation_id;
			}
			set
			{
				this._nation_id = value;
			}
		}
		
	}
}
#pragma warning restore 1591
