#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Hybrasyl	
{
	public partial class spawns
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _mob_id;
		public virtual int Mob_id
		{
			get
			{
				return this._mob_id;
			}
			set
			{
				this._mob_id = value;
			}
		}
		
		private int _map_id;
		public virtual int Map_id
		{
			get
			{
				return this._map_id;
			}
			set
			{
				this._map_id = value;
			}
		}
		
		private int _quantity;
		public virtual int Quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				this._quantity = value;
			}
		}
		
		private int _ticks;
		public virtual int Ticks
		{
			get
			{
				return this._ticks;
			}
			set
			{
				this._ticks = value;
			}
		}
		
	}
}
#pragma warning restore 1591
