//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hybrasyl.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class active_admin_comments
    {
        public int id { get; set; }
        public string resource_id { get; set; }
        public string resource_type { get; set; }
        public Nullable<int> author_id { get; set; }
        public string author_type { get; set; }
        public string body { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string @namespace { get; set; }
    }
}
