//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hybrasyl.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class drop_sets
    {
        public drop_sets()
        {
            this.mobs = new HashSet<mob>();
            this.drops = new HashSet<drop>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool enabled { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual ICollection<mob> mobs { get; set; }
        public virtual ICollection<drop> drops { get; set; }
    }
}
