//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hybrasyl.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public player()
        {
            this.legend_marks = new HashSet<legend_marks>();
            this.flags = new HashSet<flag>();
        }
    
        public int id { get; set; }
        public Nullable<int> account_id { get; set; }
        public string name { get; set; }
        public string password_hash { get; set; }
        public Hybrasyl.Enums.Sex sex { get; set; }
        public int hairstyle { get; set; }
        public int haircolor { get; set; }
        public Nullable<int> map_id { get; set; }
        public Nullable<int> map_x { get; set; }
        public Nullable<int> map_y { get; set; }
        public int direction { get; set; }
        public Hybrasyl.Enums.Class class_type { get; set; }
        public int level { get; set; }
        public int exp { get; set; }
        public int ab { get; set; }
        public int ab_exp { get; set; }
        public int max_hp { get; set; }
        public int max_mp { get; set; }
        public int cur_hp { get; set; }
        public int cur_mp { get; set; }
        public int str { get; set; }
        public int @int { get; set; }
        public int wis { get; set; }
        public int con { get; set; }
        public int dex { get; set; }
        public string equipment { get; set; }
        public string inventory { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<int> nation_id { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public Nullable<System.DateTime> last_logoff { get; set; }
        public int gold { get; set; }
    
        public virtual account account { get; set; }
        public virtual nation nation { get; set; }
        public virtual ICollection<legend_marks> legend_marks { get; set; }
        public virtual ICollection<flag> flags { get; set; }
    }
}
