//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hybrasyl.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class signpost
    {
        public int id { get; set; }
        public int map_id { get; set; }
        public int map_x { get; set; }
        public int map_y { get; set; }
        public string message { get; set; }
        public bool is_messageboard { get; set; }
        public Nullable<int> board_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual map map { get; set; }
        public virtual board board { get; set; }
    }
}
